#ifndef _WX_DATABASE_ERROR_CODES_H_
#define _WX_DATABASE_ERROR_CODES_H_

#define wxDATABASE_OK 1
#define wxDATABASE_ERROR 2
#define wxDATABASE_USER 3
#define wxDATABASE_PASSWORD 4
#define wxDATABASE_CONSTRAINT_VIOLATION 5
#define wxDATABASE_SQL_SYNTAX_ERROR 6
#define wxDATABASE_ALLOCATION_ERROR 7
#define wxDATABASE_INCOMPATIBLE_FIELD_TYPE 8
#define wxDATABASE_FIELD_NOT_IN_RESULTSET 9
#define wxDATABASE_NO_ROWS_FOUND 10
#define wxDATABASE_NON_UNIQUE_RESULTSET 11
#define wxDATABASE_UNSUPPORTED_OPERATION 12
#define wxDATABASE_ERROR_LOADING_LIBRARY 13

// Using 0 for now since this is replacing a
//  boolean for the return code and we don't want
//  to break existing code
#define wxDATABASE_QUERY_RESULT_ERROR 0 

#endif//_WX_DATABASE_ERROR_CODES_H_
